Metrics/LineLength:
  Max: 180
Documentation:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
Metrics/MethodLength:
  Max: 20
Style/BlockComments:
  Enabled: false
Style/For:
  Enabled: false
Metrics/AbcSize:
  Max: 18